### ISSUE TITLE
How to run and develop locally

### ISSUE THREAD

**Issue by yfdyh000** [cyberpower678/Cyberbot_II#51]
I tried to deploy and research this project but encountered some problems during login.
* `Error retrieving token: mwoauthserver-consumer-owner-only`, is it impossible to support for automatic approvaled OAuth app? Any possible for adding a test-only mode to login?
* Needs a "callback" URL when propose a public OAuth app, how to get it? and should I do this?

**Comment by yfdyh000** [comment]
I trying to do more code testing and contribution for help the project and reduce the labled dead links.
Wish:
Check archives on http://archive.is when auto run.
It would be nice if it could be run as an unauthenticated local mode.
More modular and streamlined for php code.

**Comment by cyberpower678** [comment]
Archive.is has no API.  IABot cannot support easy integration of it to my knowledge.

What exactly are you testing?  The interface, or the bot?  The bot's user management system relies on wiki user IDs.  So no local-only support for the moment,.

**Comment by yfdyh000** [comment]
But I see the http://archive.is/faq - "Does it support any API ?", [info](http://mementoweb.org/depot/native/archiveis/).

Like QA for pr #49, and try to write [this request](https://phabricator.wikimedia.org/T180011) (not yet started) as a PHP beginner.
I am a bit worried that too many requests will hit a personal project.

**Comment by cyberpower678** [comment]
Sorry, but that's not reliable.  Archive.is is extremely unreliable, and WebCite is really slow.  This is why the bot supports them, but doesn't actually query them.

A separate archive focused bot actually maintains the archive links in the background.

So what exactly is the problem you are facing in your test environment?

**Comment by yfdyh000** [comment]
Sad to hear the news, I really hope to support it, as archive.org is not a comprehensive archives. Maybe I should try to write a bot thereby check and fill in the data? I'm not sure I can do it. In addition, I did not see the code for automatic checking archive.is.

Any info? You mean another bot does checking urls on archive.is?

* `Error retrieving token: mwoauthserver-consumer-owner-only` if use owner-only app.
* Needs a "callback" URL when propose a public OAuth app.

This may not be necessary now, as auto checking more archives sites seems no needs and unacceptable for archive.is.

**Comment by cyberpower678** [comment]
archive.org is the most reliable and biggest service out there.

It sounds like you are trying to use the web interface which is useless without the bot.  You want to test the bot directly.  The owner-only consumer only works for the bot itself.

**Comment by cyberpower678** [comment]
The bot is started with deadlink.php and you can set it into test mode.  Just ask me if you need to know how to control the bot.

**Comment by cyberpower678** [comment]
But as a PHP beginner, I wouldn't advise using IABot as a template to learn.  IABot is really complicated.

**Comment by yfdyh000** [comment]
Ok, thank you for all your replies. I wanted to help improve the web interface primarily, followed by adding automatic checking archive.is, but as this seems unlikely.

**Comment by cyberpower678** [comment]
A future version of the interface will support anonymous access if enabled in the configuration.
