### ISSUE TITLE
detected false positive

### ISSUE THREAD

**Issue by leela52452** [cyberpower678/Cyberbot_II#62]
@cyberpower678 
i have run bot and one resiult is incorrect, see [diff](https://en.m.wikipedia.org/wiki/Special:MobileDiff/940254185). 

center4research is not permanent dead, [archive](https://web.archive.org/web/20160804014940/http://center4research.org/public-policy/testimony-briefings-statements/statementdapagliflozin/) is available.

milbank is error 301, however the issue is on their end, i sent mail "Fatal error: Uncaught Error: Call to a member function getParent()" for the article hyperlink.

perhaps i misunderstood your bot or how to use it, please look into it.

**Comment by cyberpower678** [comment]
If the website is broken, then it's dead.  If it's broken long enough that the bot marks it as such, then it failed 3 consecutive checks with a waiting period of 3 days each.  If it works again, you can just remove the tag.
