### ISSUE TITLE
False Positive (Localhost)

### ISSUE THREAD

**Issue by Lothrik** [cyberpower678/Cyberbot_II#74]
Edit: https://en.wikipedia.org/w/index.php?title=InterPlanetary_File_System&type=revision&diff=937338212&oldid=936198172

The URL: http://127.0.0.1:8080/ipfs/QmRW3V9znzFW9M5FYbitSEvd5dQrPWGvPvgQD6LM22Tv8D works perfectly fine, as long as you're running a local IPFS instance.

Testing something like this is likely beyond the scope of IABot and similar URLs should probably be blacklisted.

**Comment by cyberpower678** [comment]
Please report this to https://github.com/wikimedia/DeadlinkChecker
